### ISSUE TITLE
What is the -d ffbuild option supposed to mean?

### ISSUE THREAD

**Issue by JaiSoone** [jtanx/fontforgebuilds#11]
I have the following gdb interaction
(gdb) b main
Breakpoint 1 at 0x401584: file main.c, line 39.
(gdb) run
Starting program: C:\msys64\home\NateJoe\ff-build\ReleasePackage\bin\fontfoerge.exe -nosplash Accordance.tff
[New Thread 33488.0x3a44]
[New Thread 33488.0x80e4]
[New Thread 33488.0x831c]
[New Thread 33488.0x7564]
warning: Can not parse XML library list; XML support was disabled at compile time

Thread 1 hit Breakpoint 1, main (argc=3, argv=0x131ef00) at main.c:39
39               return fontforge_main( argc, argv );
(gdb) b fontforge_run
Breakpoint 2 at 0x4015a0
(gdb) continue
Cpontinuing.

Thread 1 hit Breakpoint 2, 0x00000000004015a0 in fontforge_main ()
(gdb) next
Single stepping until exit from function fontforge_main,
which has no line number information.
0x0000000063632f4a in ?? ()
(gdb)

HELP, I did build with the -d option, but what is that really supposed to mean?

**Comment by jtanx** [comment]
The `-d` option is/was primarily used to bundle a version of FontForge to an end user which had GDB built in to it. Since you already have msys2 and are building FontForge from scratch, you don't really need to use the `-d` flag.

My process for debugging under msys2 is:

Start an X server (needed if you're debugging the GUI or if the GUI is started; isn't needed if debugging a script)

* Create a shortcut to ReleasePackage/bin/VcXsrv/vcxsrv.exe
* RIght click on shortcut and append ` -multiwindow` to the shortcut target, e.g.: `C:\ffbuild\ReleasePackage\bin\VcXsrv\vcxsrv.exe -multiwindow`
* Double click on the shortcut - you can cancel/ignore the firewall warning; it's not needed to open the firewall for it to work
* The X server should now be running and have a tray icon. You can close the server by right clicking on the tray icon and choosing 'exit'.

Then run the following (or similar)

```bash
# Copy the GDB from http://www.equation.com/servlet/equation.cmd?fa=gdb into the bin folder
# Although MSYS2 provides gdb, it's buggy 
cp gdb.exe ReleasePackage/bin
cd ReleasePackage/bin
# Copy debug symbols into the folder
cp -r ../../debugging-symbols/.debug .
winpty gdb ./fontforge
(gdb) set args <whatever arguments you want to pass to fontforge>
(gdb) b <whatever breakpoints you want>
(gdb) r
```

**Comment by JaiSoone** [comment]
I think I've already done roughly the equivalent of this. Because I built fontforge with the -d option, ffbuild.sh already moved original-archives/binaries/gdb-64.exe and wtee to ReleasePackage/bin. I had gotten these two binaries from http://www.equation.com/servlet/equation.cmd?fa=gdb to get the 64 bit binary of release 7.12 and from https://code.google.com/archive/p/wintee/downloads to get the 32 bit binary of release1.0.1 respectively. I'm thinking this was done for me by the following in ffbuild.sh:
if (($makedebug)); then
    log_note "Adding in debugging utilities..."
    cp -f "$PATCH/ffdebugscript.txt" "$RELEASE/" || bail "Couldn't copy debug script"
    cp -f "$PATCH/fontforge-debug.bat" "$RELEASE/" || bail "Couldn't copy fontforge-debug.bat"
    cp -f "$BINARY/gdb-$ARCHNUM.exe" "$RELEASE/bin/gdb.exe" || bail "Couldn't copy GDB"
    cp -f "$BINARY/wtee.exe" "$RELEASE/bin/" || bail "Couldn't copy wtee"
    cp -rf "$DBSYMBOLS" "$RELEASE/bin/" || bail "Couldn't copy debugging symbols"
fi
I divided fonrforge-debug.bat into two parts and slightly modified them so that I could run gdb interactively. See my attachments. The only obvious difference is your directions are run from the ReleasePackage/bin directory while my ff-debug.bat script is run from the ReleasePackage directory, and the options to the xserver and fontforge are slightly different. 

[ff-debug.bat.txt](https://github.com/jtanx/fontforgebuilds/files/1224856/ff-debug.bat.txt)
[ff-end-debug.bat.txt](https://github.com/jtanx/fontforgebuilds/files/1224857/ff-end-debug.bat.txt)

**Comment by jtanx** [comment]
Hmm... If you can't debug under GDB that suggests that the debugging symbols aren't being loaded correctly.

Can you please manually verify that there are files under ReleasePackage\bin\.debug? It wouldn't hurt also to rerun `./ffbuild.sh` (it should be fairly quick now that everything is built) and manually copy `debugging-symbols/.debug` into `ReleasePackage/bin`.

When I run under GDB, I get the following messages:

```
warning: section .gnu_debuglink not found in C:\ffbuild\ReleasePackage\bin\.debug\libfontforgeexe-2.debug
warning: section .gnu_debuglink not found in C:\ffbuild\ReleasePackage\bin\.debug\libgdraw-5.debug
warning: section .gnu_debuglink not found in C:\ffbuild\ReleasePackage\bin\.debug\libgutils-2.debug
warning: section .gnu_debuglink not found in C:\ffbuild\ReleasePackage\bin\.debug\libgunicode-4.debug
warning: section .gnu_debuglink not found in C:\ffbuild\ReleasePackage\bin\.debug\libfontforge-2.debug
warning: section .gnu_debuglink not found in C:\ffbuild\ReleasePackage\bin\.debug\libuninameslist-1.debug
...
```

If all of that still fails, you can try commenting out line 681 and uncommenting 682: https://github.com/jtanx/fontforgebuilds/blob/89acdb4c5b46894f1fbaa4b4d96fcc02d8f51345/ffbuild.sh#L681-L682 then rerun ffbuild.sh

This will leave the debugging symbols in the binaries instead of separating them out into a different file.

**Comment by JaiSoone** [comment]
Well, nothing I do gets me any debug info for fontforge_main(). This morning, I wiped out ff-build and and reloaded it. I wanted to build without the -d option and only use the versions of thing listed in the build instructions. For 64 bit builds though, one at a minimum must change ffbuild.sh to reference:
	1) potrace-1.15.win64.tar.gz as potrace-1.11.win64.tar.gz is
	    no longer offered as a prebuild binary
        2) actually download pango-1.40.7.tar.xz instead of pango-1.40.6.tar.xz
            as has been updated to reference the newer version.
	     Note that as if today pango-1.40.10.tar.xz is available.
	3) python3.6 as mingw64/lib no longer contains a python3.5
Also change strip-python.sh to reference:
	1) python3.6 for 64 bit builds.

This represents a little change as I've been also using pango-1.40.9.tar.xz.
Interestingly, I did not have to let the build fail before retrieving mingw-w64-x86_64-xtrans-git-r252.2836667-1 and mingw-w64-x86_64-pkg-config-0.29.2-1. Not sure what changed though. I could wipe out all of MSYS2 and start over again. When I was working on HP-UX we had a program called elfdump that would allow us to dump various section header information in a .o or .exe type file. From this we could tell if there was a dwarf section or an unwind section. At least one could tell if  something wasn't compiled right without understanding the complete build process. Any such utility in this environment?

**Comment by jtanx** [comment]
Nothing in that list strikes me as having any effect on debugging symbols. The primary indicator for the presence of debug symbols is the size of the binaries (DLLs/EXEs). 

For example, for 32 bit builds, under `debugging-symbols/.debug`, I can see that `libfontforge-2.debug` is ~8MB and `libfontforgeexe-2.debug` is ~7MB. Under `ReleasePackage/bin`, the stripped `libfontforge-2.dll` and `libfontforgeexe-2.dll` is ~3-4MB

If you altered ffbuild as per https://github.com/jtanx/fontforgebuilds/blob/89acdb4c5b46894f1fbaa4b4d96fcc02d8f51345/ffbuild.sh#L681-L682 then rerun ffbuild.sh

Then the size of the dlls are around 11-12MB.

If you can see the size differences, then perhaps there is something wrong with the version of GDB being used. Perhaps you could try installing:

```
pacman -S mingw-w64-x86_64-gdb
```

Then:

```
cd ReleasePackage
which gdb      #Confirm it's from /mingw64/bin/gdb
winpty gdb ./fontforge
```

**Comment by JaiSoone** [comment]
My debug files are:
$ lh
total 31M
-rwxr-xr-x 1 NateJoe None 403K Aug 16 08:37 fontforge.debug
-rwxr-xr-x 1 NateJoe None 5.3M Aug 16 08:37 libcairo-2.debug
-rwxr-xr-x 1 NateJoe None 8.6M Aug 16 08:37 libfontforge-2.debug
-rwxr-xr-x 1 NateJoe None 7.9M Aug 16 08:37 libfontforgeexe-2.debug
-rwxr-xr-x 1 NateJoe None 2.5M Aug 16 08:37 libgdraw-5.debug
-rwxr-xr-x 1 NateJoe None 1.4M Aug 16 08:37 libgunicode-4.debug
-rwxr-xr-x 1 NateJoe None 1.5M Aug 16 08:37 libgutils-2.debug
-rwxr-xr-x 1 NateJoe None 918K Aug 16 08:37 libpango-1.0-0.debug
-rwxr-xr-x 1 NateJoe None 583K Aug 16 08:37 libpangocairo-1.0-0.debug
-rwxr-xr-x 1 NateJoe None 593K Aug 16 08:37 libpangoft2-1.0-0.debug
-rwxr-xr-x 1 NateJoe None 514K Aug 16 08:37 libpangowin32-1.0-0.debug
-rwxr-xr-x 1 NateJoe None 446K Aug 16 08:37 libpangoxft-1.0-0.debug

I could run it under winpty, but I haven't been.

As Arch Linux is effectively dropping support for i686 beginning Niovember 2017, will fontforge windows build support be giving more emphasis on x86_64?

**Comment by jtanx** [comment]
So it looks like debug symbols are being generated ok.

What arch Linux does is likely not going to affect msys2's support of 32 bit builds; it uses a port of pacman and I don't foresee support for 32 bit Windows binaries being dropped any time soon.

**Comment by JaiSoone** [comment]
I think they were saying that most developers were building on 64 bit machines for programs running on 32 or 64 bit machines. They putting 32 bit build support onto a side show of some sort.

**Comment by JaiSoone** [comment]
The setup of fontforge is rather confusing. There are two .c files containing versions of fontforge_main(), one in startui.c and one in strtnoui.c. Both would seem to go into libfontforgeexe_la which I guess goes into libfontforgeexe-2.dll, but actually only the startui.o version survives. So, what's in fontforge.exe, run_fontforge.exe, libfontforge-2.dll, and libfontforgeexe-2.dll. How are they related? I suppose I need to find a windows utility to see what's happening with the .dll's. It looks like I start off in the .exe fine with gdb, but immediately call into a .dll for which gdb gets lost finding debug info. Am I missing appropriately set environment variables or something?

**Comment by JaiSoone** [comment]
Just to be clear, gdb thinks it knows the address of fontforge_main, allows me to set a break point there, I continue the program and in fact hit that break point. I have know idea though if gdb really knows what is talking about. Anyway gdb does not know though were the line number debug table is for fontforge_main. Kind of strange!

**Comment by jtanx** [comment]
Hmm, I've now done a 64-bit build, and I can't seem to reproduce this issue; it seems to debug just fine. For reference, I updated ffbuild to https://github.com/jtanx/fontforgebuilds/commit/1c5a2786503aa797fa96812651c93bb7ce7f1811, so it might be worth updating your local copy, although it should just be the change that you've already mentioned (python 3.5->3.6).

I then did

```
./ffbuild --makedebug
```

And I used this gdb: ftp://ftp.equation.com/gdb/snapshot/64/gdb.exe

For original-archives/binaries/gdb-64.exe

I then used the script that you posted: https://github.com/jtanx/fontforgebuilds/files/1224856/ff-debug.bat.txt

and did:

```
b fontforge_main
r
```

and it spat out:

```
Running FontForge in debug mode, expect it to be slower!
GNU gdb (GDB) 7.7.50.20140303-cvs
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

This binary was built by Equation Solution <http://www.Equation.com>...
Reading symbols from D:\ReleasePackage\\bin\fontforge.exe...done.
(gdb) b fontforge_main
Breakpoint 1 at 0x4015a0
(gdb) r
Starting program: D:\ReleasePackage\bin\fontforge.exe -nosplash Accordance.tff
[New Thread 2388.0x20ac]
[New Thread 2388.0x1a3c]
[New Thread 2388.0x2b8]
[New Thread 2388.0x11dc]
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libfontforgeexe-2.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libgdraw-5.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libgutils-2.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libgunicode-4.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libfontforge-2.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libuninameslist-1.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libcairo-2.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libpango-1.0-0.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libpangocairo-1.0-0.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libpangoxft-1.0-0.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libX11-6.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libXft-2.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libspiro-0.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libX11-xcb-1.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libxcb-render-0.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libxcb-1.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libpangoft2-1.0-0.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libpangowin32-1.0-0.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libXrender-1.debug
warning: section .gnu_debuglink not found in D:\ReleasePackage\bin\.debug\libXau-6.debug

Breakpoint 1, 0x00000000004015a0 in fontforge_main ()
(gdb) n
Single stepping until exit from function fontforge_main,
which has no line number information.
fontforge_main (argc=0, argv=0xf) at startui.c:863
863     int fontforge_main( int argc, char **argv ) {
(gdb)

Breakpoint 1, fontforge_main (argc=3, argv=0x262a800) at startui.c:866
866         const char *load_prefs = getenv("FONTFORGE_LOADPREFS");
(gdb)
```

**Comment by JaiSoone** [comment]
I'm going to start over from scratch. I've only seen the 4 threads start up. I've never seen the .gnu_debuglink not found warnings.

**Comment by JaiSoone** [comment]
Good news. This version of GDB works. It seems that this build process always generates debug information. The only thing the -d or --makedebug options does is move that debug information into the ReleasePackage. This probably means that FontForge is not optimized. Is it that FontForge doesn't do any compute intensive operations? Just wondering, trying to answer my original question.

**Comment by jtanx** [comment]
I'm glad you got it working.

The `-d` option at the time was more to automate making a package that could be released to end users so that we could get a back trace. If you're building fontforge from scratch, there's not much use to using that flag.

> This probably means that FontForge is not optimized

Having debugging symbols always generated is by design - it's controlled by `-g` in the `CFLAGS` parameter. Whether or not debugging symbols are made has little effect on optimisation, so this statement is not quite correct. Compiler optimisation levels would be controlled by setting e.g. `-O0` for no (or the least amount provided by gcc) optimisation. I believe it currently defaults to `-O2`.

**Comment by JaiSoone** [comment]
Thanks again. For the record though, 1) optimization can make code move around, making the line number table some what inaccurate, and 2) can make the symbol table not so useful (i.e., variables can just disappear).  gcc recommends using -Og which "enables optimizations that do not interfere with debugging."

**Comment by jtanx** [comment]
Sure, although in practice, even at `-O2`, you can usually figure out what's going on or what's caused the crash. I'd hazard a guess and say that the performance drawbacks of `-Og` are not worth it for 'Release' builds, since most end users aren't even interested or know how to get a stack trace anyway. 

Something I've noticed too, is that sometimes, certain crashes only happen at higher optimisation levels, and will disappear if you lower it (usually caused by code that relies on undefined behaviour). So sometimes you have no choice :)
