### ISSUE TITLE
FontForge is now available from MSYS2

### ISSUE THREAD

**Issue by JaiSoone** [jtanx/fontforgebuilds#20]
As of March 8, 2022, FontForge is available in various binary packages. I would guess it has full documentation along with the binaries. It doesn't seem to make the various utilities though. Adding "-DENABLE_FONTFORGE_EXTRAS=yes" to EXTRA_CMAKE_OPTS in ffbuild.sh for cmake successfully gets them built. Some of these utilities are rather out of date though. While running ffbuild.sh I saw where configure could not find sphinx, and seeing it as a build dependency of the MSYS2 fontfoge binary package for UCRT64, I decided to install "mingw-w64-ucrt-x86_64-python-sphinx" on my system and then build everything via ffbuild.sh. Don't know if this made a difference though as I never went looking for documentation before. Seems sphinx is a python documentation helper of some sort.

**Comment by jtanx** [comment]
cool
