### ISSUE TITLE
ffbuild calls bootstrap that's not there

### ISSUE THREAD

**Issue by alexaschee** [jtanx/fontforgebuilds#4]
I was trying to build 32-bit fontforge from scratch on a new-installed msys2. After hours running, ffbuild gave me this:

![image](https://cloud.githubusercontent.com/assets/13317191/8654713/bacefd04-29be-11e5-86d1-99333aaebc7c.png)

The current dir was /g/fontforge_src/work/mingw32/fontforge/.  I searched and found only one bootstrap in /g/fontforge_src/work/mingw32/fontforge/gnulib/build-aux/, but I think that's not the right one.

Did I do anything wrong?

**Comment by jtanx** [comment]
It looks like you are using an outdated version of my script. The current version uses precompiled versions of libX11 which greatly saves on compile time. In any case, that bootstrap file should be [this](https://github.com/fontforge/fontforge/blob/master/bootstrap) file. 

But since you have compiled everything from source:
1. Remove `/g/fontforge_src/work/mingw32/fontforge` - it should be re-cloned by ffbuild. When ffbuild has run again (step 3), just check that `/g/fontforge_src/work/mingw32/fontforge` is a clone of this repository:https://github.com/jtanx/fontforge.
   
   If you want to build from FontForge master, either edit `ffbuild.sh` first to point to https://github.com/fontforge/fontforge, or clone and checkout your desired version into `/g/fontforge_src/work/mingw32/fontforge`.
2. Update the build script (I presume you cloned from GitHub and not SourceForge):
   
   ```
     cd /g/fontforge_src
     git pull origin master
   ```
3. Execute ffbuild like so:
   
   ```
    ./ffbuild.sh --depsfromscratch
   ```

**Comment by alexaschee** [comment]
Thanks a lot, jtanx. This time I built it by following your instructions. So far 2 unexpected points:
1. The build script didn't copy all needed DLLs into ReleasePackage/bin/, I had to copy them manually to get the exe/bat work;
2. The windows titles are always "VcXsrv X" -- this was supposed to be fixed last month, and my src files are the newest. (Perhaps it's my own fault: the downloaded FontForgeSetup-14-06-2015.exe shows wrong window titles, too. Repeat un/reinstall didn't change anything in my case.)

Thank you again. The building process is exciting.

**Comment by jtanx** [comment]
@alexaschee, thanks for the feedback! I think I know how to fix 1.

For 2., when did you download the VcXsrv binaries? I updated them not so long ago to fix the issue, so try re-downloading these files, then delete `/g/fontforge_src/work/mingw32/VcXsrv` and `/g/fontforge_src/ReleasePackage/bin/VcXsrv`, then run the build script again.

If that still doesn't work, can you run `ShowLocale.exe` from [here](https://github.com/jtanx/fontforgebuilds/releases/tag/v0.01) and tell me what the result is? (Source [here](https://github.com/jtanx/fontforgebuilds/blob/master/patches/ShowLocale/ShowLocale/showlocale.c))

**Comment by jtanx** [comment]
@alexaschee I've just updated the build script which should hopefully fix the 1st issue of DLLs not being copied. Please try updating your copy to see if this now works. Thanks!

**Comment by alexaschee** [comment]
Hi, [@jtanx](https://github.com/jtanx):
1: Yes, the new build script works - thanks a lot for what you've done.

2: Not solved. I first downloaed [VcXsrv](https://sourceforge.net/projects/fontforgebuilds/files/build-system-extras/VcXsrv-1.14.2-minimal.tar.xz) 2 days ago, on July 13; it's still the most recent.

3: The Showlocale.exe(64-bit?) can't run on my 32-bit system.

Guess I have to get along with what I have now till your next release.

**Comment by jtanx** [comment]
@alexaschee thanks for testing! It looks like I forgot to compile ShowLocale with the v210_xp toolset (it's compiled in Visual Studio). I've recompiled it with Visual Studio, so could you please try this again (binary [here](https://github.com/jtanx/fontforgebuilds/releases/download/v0.01/ShowLocalev2.exe))?

It should also generate a file `localelist.txt` in the same directory - if you could upload this to say Github Gist that would be great too.

**Comment by zoghal** [comment]
@jtanx please create page in wiki : how to build [step by step]. thanks

**Comment by jtanx** [comment]
@zoghal it's slightly out of date, but there's [this](http://sourceforge.net/p/fontforgebuilds/wiki/Using%20the%20build%20script/).

**Comment by alexaschee** [comment]
[@jtanx](https://github.com/jtanx), ShowLocalev2.exe gives  an error msg, something like "procedure entrypoint GetLocaleInfoEx couldn't be located in Kenel32.dll".

**Comment by jtanx** [comment]
Ah, @alexaschee  sorry about that - I didn't realise some of the functions didn't exist on XP. I've made a version specific for XP [here](https://github.com/jtanx/fontforgebuilds/releases/download/v0.01/ShowLocalev2_xp.exe) - this one won't generate `localelist.txt` so don't worry about that part.

**Comment by alexaschee** [comment]
Hi, [@jtanx](https://github.com/jtanx), here's the result:

![locale](https://cloud.githubusercontent.com/assets/13317191/8744475/fc73b400-2ca9-11e5-8afb-aca4ba3e4e90.JPG)

so it's a long version of zh_cn.936 for human, huh?

**Comment by jtanx** [comment]
Ah, that explains it - in `ReleasePackage\bin\VcxSrv\locale\locale.alias` try appending 

```
 Chinese_People's-Republic-of-China.936:    zh_CN.eucCN
```

To the file and see if that fixes it.

**Comment by alexaschee** [comment]
[@jtanx](https://github.com/jtanx), it works! thank you so much.

**Comment by alexaschee** [comment]
[@jtanx](https://github.com/jtanx), I have installed 2015-6-14 release on my office machine (no internet connection, same LC_ALL), but appending

`Chinese_People's-Republic-of-China.936:    zh_CN.eucCN`

to the `\bin\VcxSrv\locale\locale.alias`  won't fix the windows title.  Any easier way to fix this than copying my own build from home?

**Comment by jtanx** [comment]
Stale issue, things have changed quite a bit since then (and I think are no longer relevant, particularly since switching to gdk)
