### ISSUE TITLE
FontForge without X under windows (vcxsrv)

### ISSUE THREAD

**Issue by ChSch3000** [jtanx/fontforgebuilds#7]
From the FontForge manpage (fontforge -help)

> If a scriptfile is specified then FontForge will not open the X display nor will it process any additional arguments. It will execute the scriptfile and give it any remaining arguments..."

But if i run a fontforge script under windows, the X-Server (vcsrc) starts every time. This prevents that i can start multiple instances of font forge. If already an instance is running i get the following error from the vcsrv.exe:

> "cannot establish any listening sockets - make sure an x server isn't already running"

It would be great if somebody could fix this problem, because for me it is indispensable to run the FF Script in parallel.

**Comment by jtanx** [comment]
Can you provide an example of how you're calling FontForge? If you're calling fontforge.bat, then it should automatically handle multiple instances of vcxsrv properly - if it isn't then that's an issue.

However, if you only need to run scripts, you can bypass vcxsrv completely by calling the fontforge executable directly - e.g.

```
bin/fontforge.exe -lang=pe -script myscript.pe
bin/fontforge.exe -lang=py -script myscript.py
bin/fontforge.exe -lang=pe -c "Open('test.sfd');Generate('test.otf');"
bin/fontforge.exe -lang=py -c "import fontforge; ..."
```

etc

**Comment by ChSch3000** [comment]
I call the script by calling the fontfotge.bat

> fontforge.bat -script myscript.pe

But it seems to be working if i call the fontforge.exe directly. With the following command no X Server is started.

> bin/fontforge.exe -script myscript.pe

I guess there is an error in the batch file.

**Comment by jtanx** [comment]
Hmm that's strange. It works for me...

**Comment by ghost** [comment]
here is a simple 'generate' example:

```batch
@echo off
chcp 65001 2>nul >nul

:LOOP
::has argument ?
if ["%~1"]==[""] (
  echo done.
  goto END;
)
::argument exist ?
if not exist %~s1 (
  echo not exist
  goto NEXT;
)
::file exist ?
echo exist
if exist %~s1\NUL (
  echo is a directory
  goto NEXT;
)
::OK
echo is a file

::--------------------------------------------------------------------------------

set FILE_INPUT="%~1"
set FILE_BACKUP="%~1_backup"

@echo on
::call fontforge.bat -lang "ff" -c "Open($1); Reencode(\"unicode\"); AutoHint(); Generate($1:r + \".pfb\");" %FILE_INPUT%
call fontforge.bat -lang "ff" -c "Open($1); Generate($1:r + \".pfb\"); Generate($1:r + \".ps\"); Generate($1:r + \".shx\");" %FILE_INPUT%

::--------------------------------------------------------------------------------

echo.

:NEXT
shift
goto LOOP

:END
pause
```

it accepts around 100+ font-files in various formats,
and generated an AutoCad-capable fonts (SHX, PFB, PS), 
although each action works in a sync. way - the tasks finishes before continuing to the next one, 
I still get many <code>VcXsrv</code> popups...

<img src="https://i.imgur.com/ZfI6NHvl.gif" /> <br/>

myabe combining <code>Quit(0);</code> in the last line of the script?

<img src="https://i.imgur.com/sHgwulZ.gif" /> <br/>

Nope...

also, 
no important output in the console though...
```txt
C:\Users\Elad\Desktop\fonts-AutoCad\fonts\_4>call fontforge.bat -lang "ff" -c "Open($1); Genera
te($1:r + \".pfb\"); Generate($1:r + \".ps\"); Generate($1:r + \".shx\");" "C:\Users\Elad\Deskt
op\fonts-AutoCad\fonts\_4\MOD20.TTF"
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 08:20 UTC 31-Jul-2017-ML-TtfDb-D.
 Based on source from git with hash: 8b6e7f07a5511e4de9c8a710db6ca8e770de8f4e
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
  Ignoring 'LTSH' linear threshold table
  Ignoring 'VDMX' vertical device metrics table
  Ignoring 'hdmx' horizontal device metrics table
Glyph 2 is called ".notdef", a singularly inept choice of name (only glyph 0
  may be called .notdef)
  FontForge will rename it.
The glyph named fraction is mapped to U+2215.
  But its name indicates it should be mapped to U+2044.
The glyph named fi is mapped to U+F001.
  But its name indicates it should be mapped to U+FB01.
The glyph named fl is mapped to U+F002.
  But its name indicates it should be mapped to U+FB02.
The glyph named periodcentered is mapped to U+2219.
  But its name indicates it should be mapped to U+00B7.

done.
Press any key to continue . . .
```

**Comment by jtanx** [comment]
Use the latest version and try again, vcxsrv is no longer used
